[11/23/22 17:38:03] WARNING  Something went wrong with getting the username to send to Heap. Exception: [Errno 6] No such plugin.py:107
                             device or address                                                                                         
[11/23/22 17:38:03] INFO     Kedro project projetaai-starter                                                             session.py:338
[11/23/22 17:38:04] INFO     Loading data from 'iris_data_multi' (PartitionedDataSet)...                            data_catalog.py:343
                    INFO     Loading data from 'params:config' (MemoryDataSet)...                                   data_catalog.py:343
                    INFO     Running node: multipipe1: fn([iris_data_multi,params:config]) -> [X_test-slicer]               node.py:327
                    INFO     Saving data to 'X_test-slicer' (JSONDataSet)...                                        data_catalog.py:382
[11/23/22 17:38:05] INFO     Completed 1 out of 10 tasks                                                        sequential_runner.py:85
                    INFO     Running node: multipipe1-synchronization: fn(None) ->                                          node.py:327
                             [X_test,X_train,iris_data_multi_with_country,y_pred,y_test,y_train]                                       
                    INFO     Saving data to 'X_test' (PartitionedDataSet)...                                        data_catalog.py:382
                    INFO     Saving data to 'X_train' (PartitionedDataSet)...                                       data_catalog.py:382
                    INFO     Saving data to 'iris_data_multi_with_country' (PartitionedDataSet)...                  data_catalog.py:382
                    INFO     Saving data to 'y_pred' (PartitionedDataSet)...                                        data_catalog.py:382
                    INFO     Saving data to 'y_test' (PartitionedDataSet)...                                        data_catalog.py:382
                    INFO     Saving data to 'y_train' (PartitionedDataSet)...                                       data_catalog.py:382
                    INFO     Completed 2 out of 10 tasks                                                        sequential_runner.py:85
                    INFO     Loading data from 'X_test-slicer' (JSONDataSet)...                                     data_catalog.py:343
                    INFO     Loading data from 'iris_data_multi' (PartitionedDataSet)...                            data_catalog.py:343
                    INFO     Loading data from 'params:config' (MemoryDataSet)...                                   data_catalog.py:343
                    INFO     Running node: add_country-slice-0: add_country([X_test-slicer,iris_data_multi,params:config])  node.py:327
                             -> [iris_data_multi_with_country-slice-0]                                                                 
                    INFO     Processing "iris 1" on "add_country-slice-0"                                              multinode.py:898
                    INFO     Using configurator "['1']" for "iris 1"                                                   multinode.py:913
                    INFO     Processing "iris 2" on "add_country-slice-0"                                              multinode.py:898
                    INFO     Using configurator "['2']" for "iris 2"                                                   multinode.py:913
                    INFO     Saving data to 'iris_data_multi_with_country-slice-0' (PartitionedDataSet)...          data_catalog.py:382
                    INFO     Completed 3 out of 10 tasks                                                        sequential_runner.py:85
                    INFO     Loading data from 'X_test-slicer' (JSONDataSet)...                                     data_catalog.py:343
                    INFO     Loading data from 'iris_data_multi' (PartitionedDataSet)...                            data_catalog.py:343
                    INFO     Loading data from 'params:config' (MemoryDataSet)...                                   data_catalog.py:343
[11/23/22 17:38:06] INFO     Running node: add_country-slice-1: add_country([X_test-slicer,iris_data_multi,params:config])  node.py:327
                             -> [iris_data_multi_with_country-slice-1]                                                                 
                    INFO     Processing "iris 3" on "add_country-slice-1"                                              multinode.py:898
                    INFO     Using configurator "['3']" for "iris 3"                                                   multinode.py:913
                    INFO     Saving data to 'iris_data_multi_with_country-slice-1' (PartitionedDataSet)...          data_catalog.py:382
                    INFO     Completed 4 out of 10 tasks                                                        sequential_runner.py:85
                    INFO     Loading data from 'X_test-slicer' (JSONDataSet)...                                     data_catalog.py:343
                    INFO     Loading data from 'iris_data_multi_with_country-slice-0' (PartitionedDataSet)...       data_catalog.py:343
                    INFO     Loading data from 'params:para' (MemoryDataSet)...                                     data_catalog.py:343
                    INFO     Running node: split-slice-0:                                                                   node.py:327
                             split_data([X_test-slicer,iris_data_multi_with_country-slice-0,params:para]) ->                           
                             [X_train-slice-0,X_test-slice-0,y_train-slice-0,y_test-slice-0]                                           
                    INFO     Processing "iris 1" on "split-slice-0"                                                    multinode.py:898
                    INFO     Processing "iris 2" on "split-slice-0"                                                    multinode.py:898
                    INFO     Saving data to 'X_train-slice-0' (PartitionedDataSet)...                               data_catalog.py:382
                    INFO     Saving data to 'X_test-slice-0' (PartitionedDataSet)...                                data_catalog.py:382
                    INFO     Saving data to 'y_train-slice-0' (PartitionedDataSet)...                               data_catalog.py:382
[11/23/22 17:38:07] INFO     Saving data to 'y_test-slice-0' (PartitionedDataSet)...                                data_catalog.py:382
                    INFO     Completed 5 out of 10 tasks                                                        sequential_runner.py:85
                    INFO     Loading data from 'X_test-slicer' (JSONDataSet)...                                     data_catalog.py:343
                    INFO     Loading data from 'iris_data_multi_with_country-slice-1' (PartitionedDataSet)...       data_catalog.py:343
                    INFO     Loading data from 'params:para' (MemoryDataSet)...                                     data_catalog.py:343
                    INFO     Running node: split-slice-1:                                                                   node.py:327
                             split_data([X_test-slicer,iris_data_multi_with_country-slice-1,params:para]) ->                           
                             [X_train-slice-1,X_test-slice-1,y_train-slice-1,y_test-slice-1]                                           
                    INFO     Processing "iris 3" on "split-slice-1"                                                    multinode.py:898
                    INFO     Saving data to 'X_train-slice-1' (PartitionedDataSet)...                               data_catalog.py:382
                    INFO     Saving data to 'X_test-slice-1' (PartitionedDataSet)...                                data_catalog.py:382
[11/23/22 17:38:08] INFO     Saving data to 'y_train-slice-1' (PartitionedDataSet)...                               data_catalog.py:382
                    INFO     Saving data to 'y_test-slice-1' (PartitionedDataSet)...                                data_catalog.py:382
                    INFO     Completed 6 out of 10 tasks                                                        sequential_runner.py:85
                    INFO     Loading data from 'X_test-slicer' (JSONDataSet)...                                     data_catalog.py:343
                    INFO     Loading data from 'X_train-slice-0' (PartitionedDataSet)...                            data_catalog.py:343
                    INFO     Loading data from 'X_test-slice-0' (PartitionedDataSet)...                             data_catalog.py:343
                    INFO     Loading data from 'y_train-slice-0' (PartitionedDataSet)...                            data_catalog.py:343
                    INFO     Running node: make_predictions-slice-0:                                                        node.py:327
                             make_predictions([X_test-slicer,X_train-slice-0,X_test-slice-0,y_train-slice-0]) ->                       
                             [y_pred-slice-0]                                                                                          
                    INFO     Processing "iris 1" on "make_predictions-slice-0"                                         multinode.py:898








     sepal_length  sepal_width  petal_length  petal_width country
0             4.6          3.2           1.4          0.2  brasil
1             4.6          3.1           1.5          0.2  brasil
2             5.4          3.4           1.5          0.4  brasil
3             5.0          3.0           1.6          0.2  brasil
4             5.7          4.4           1.5          0.4  brasil
..            ...          ...           ...          ...     ...
115           5.2          3.4           1.4          0.2  brasil
116           6.0          2.9           4.5          1.5  brasil
117           6.3          2.5           5.0          1.9  brasil
118           5.0          3.3           1.4          0.2  brasil
119           5.6          2.7           4.2          1.3  brasil

[120 rows x 5 columns]








                    ERROR    Node 'make_predictions-slice-0:                                                                node.py:352
                             make_predictions([X_test-slicer,X_train-slice-0,X_test-slice-0,y_train-slice-0]) ->                       
                             [y_pred-slice-0]' failed with error:                                                                      
                             unsupported operand type(s) for -: 'str' and 'str'                                                        
                    WARNING  There are 4 nodes that have not run.                                                         runner.py:178
                             You can resume the pipeline run by adding the following argument to your previous command:                
                               --from-nodes                                                                                            
                             "make_predictions-slice-0,make_predictions-slice-1,report_accuracy-slice-0,report_accuracy-s              
                             lice-1"                                                                                                   
